from sokoengine import Direction, AtomicMove
from sokoengine.variant.tessellation import Tessellation
from sokoengine.variant.hexoban_tessellation import HexobanTessellation
from helpers import TessellationSpecMixin
from autogenerated import HexobanTessellationAutogeneratedSpecMixin
from hamcrest import assert_that, equal_to


class DescribeHexobanTessellation(
    TessellationSpecMixin, HexobanTessellationAutogeneratedSpecMixin
):

    illegal_directions = [
        Direction.UP, Direction.DOWN
    ]

    legal_directions = [
        Direction.LEFT, Direction.RIGHT,
        Direction.NORTH_WEST, Direction.NORTH_EAST,
        Direction.SOUTH_WEST, Direction.SOUTH_EAST,
    ]

    legal_moves = [
        AtomicMove(Direction.LEFT, False),
        AtomicMove(Direction.RIGHT, False),
        AtomicMove(Direction.NORTH_WEST, False),
        AtomicMove(Direction.NORTH_EAST, False),
        AtomicMove(Direction.SOUTH_WEST, False),
        AtomicMove(Direction.SOUTH_EAST, False),
        AtomicMove(Direction.LEFT, True),
        AtomicMove(Direction.RIGHT, True),
        AtomicMove(Direction.NORTH_WEST, True),
        AtomicMove(Direction.NORTH_EAST, True),
        AtomicMove(Direction.SOUTH_WEST, True),
        AtomicMove(Direction.SOUTH_EAST, True)
    ]

    legal_characters = [
        'l', 'r', 'u', 'n', 's', 'd', 'L', 'R', 'U', 'N', 'S', 'D'
    ]

    tessellation = Tessellation.factory('Hexoban')

    class Describe_graph_type(object):
        def test_is_directed(self):
            assert_that(
                HexobanTessellation().graph_type().is_directed(),
                equal_to(True)
            )


        def test_doesnt_allow_parallel_edges(self):
            assert_that(
                HexobanTessellation().graph_type().is_multigraph(),
                equal_to(False)
            )
