from hamcrest import assert_that, equal_to

from sokoengine import Direction, AtomicMove
from sokoengine.core import Tessellation
from sokoengine.variant import SokobanTessellation
from helpers import TessellationSpecMixin

from autogenerated import SokobanTessellationAutogeneratedSpecMixin


class DescribeSokobanTessellation(
    TessellationSpecMixin, SokobanTessellationAutogeneratedSpecMixin
):

    illegal_directions = [
        Direction.NORTH_WEST, Direction.NORTH_EAST,
        Direction.SOUTH_WEST, Direction.SOUTH_EAST
    ]

    legal_directions = [
        Direction.LEFT, Direction.RIGHT, Direction.UP, Direction.DOWN
    ]

    legal_moves = [
        AtomicMove(Direction.LEFT, False),
        AtomicMove(Direction.RIGHT, False),
        AtomicMove(Direction.UP, False),
        AtomicMove(Direction.DOWN, False),
        AtomicMove(Direction.LEFT, True),
        AtomicMove(Direction.RIGHT, True),
        AtomicMove(Direction.UP, True),
        AtomicMove(Direction.DOWN, True),
    ]

    legal_characters = [
        'l', 'r', 'u', 'd', 'L', 'R', 'U', 'D'
    ]

    tessellation = Tessellation.factory('Sokoban')

    class Describe_graph_type(object):
        def test_is_directed(self):
            assert_that(
                SokobanTessellation().graph_type().is_directed(),
                equal_to(True)
            )


        def test_doesnt_allow_parallel_edges(self):
            assert_that(
                SokobanTessellation().graph_type().is_multigraph(),
                equal_to(False)
            )
