cloc --by-file --skip-uniqueness --quiet sokoenginepy
cloc --by-file --skip-uniqueness --quiet --not-match-f="autogenerated.*.py" tests
cloc --list-file=scripts/cloc_dirs.txt --not-match-f="autogenerated.*.py" 
