name: docs-sphinx

on:
  push:
    branches:
      - development
    paths:
      - '**.py'
      - '**.md'
      - '**.rst'


jobs:

  # Replicate build of Sphinx docs on ReadTheDocs so we get early fail if we broke it
  sphinx_docs:
    name: Sphinx docs
    runs-on: ubuntu-latest
    env:
      SOKOENGINEPYEXT_SKIP: true

    steps:
      - uses: actions/checkout@v3

      - name: set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: ensure latest pip
        run: python -m pip install --upgrade pip

      - name: install wheel
        run: pip install wheel

      - name: install docs environment
        run: pip install .[docs]

      - name: build Sphinx documentation
        run: sphinx-build -E -b html docs dist/docs
